"""Initial migration

Revision ID: b152899a8682
Revises: 
Create Date: 2025-04-26 15:22:47.310709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b152899a8682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_doses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('taken_doses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('missed_doses', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_column('missed_doses')
        batch_op.drop_column('taken_doses')
        batch_op.drop_column('total_doses')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
